### ISSUE TITLE
Nested Deconstruction in Constructor Causes Error During Generation

### ISSUE THREAD

**Issue by theovier** [achlubek/aero-di#4]
Hi,

I've just stumbled across this lib and wanted to give it a try.
I followed the instruction steps

1. add `aero-di` as dependency
2. run `aero-di-generate --baseDir src` (via yarn script)

and received the error: 

```
Generating reflection to reflectionData.ts for directory .../backend/src
.../node_modules/aero-di/dist/reflection/extractClass.js:34
        name: firstIdentifier.getText(),
                              ^

TypeError: Cannot read properties of undefined (reading 'getText')
    at extractParameter (.../node_modules/aero-di/dist/reflection/extractClass.js:34:31)
    at .../node_modules/aero-di/dist/reflection/extractClass.js:48:56
    at Array.map (<anonymous>)
    at extractConstructor (.../node_modules/aero-di/dist/reflection/extractClass.js:48:41)
    at extractClass (...node_modules/aero-di/dist/reflection/extractClass.js:168:64)
    at visitor (.../node_modules/aero-di/dist/reflection/generateReflection.js:33:67)
    at visitNodes (.../node_modules/typescript/lib/typescript.js:27594:24)
    at forEachChildInSourceFile (.../node_modules/typescript/lib/typescript.js:28214:18)
    at Object.forEachChild (.../node_modules/typescript/lib/typescript.js:27679:37)
    at generateReflectionDataForFiles (.../node_modules/aero-di/dist/reflection/generateReflection.js:52:12)
```

Could this be the case because some constructors use deconstruction?

```ts
constructor ({id}: {id: string}) {
  ...
}
```

Let me know if you need more info.

Kind regards,
Theo

**Comment by theovier** [comment]
Thanks for the fast reply. I'll try to come up with a minimal reproduction example next weekend.

**Comment by achlubek** [comment]
Great! Looking forward for it, meanwhile I will try to analyze what can cause this issue.

**Comment by theovier** [comment]
Okay, so I just tested something and I think this is casuing the error:

```ts
export class FooBar {
	constructor({ foo: { bar } }: { foo: { bar: string } }) {}
}
```

**Comment by achlubek** [comment]
All right, I can reproduce it, thank you. I'm getting into it.

**Comment by achlubek** [comment]
Can you check if aero-di@3.0.4 fixes the issue?

**Comment by achlubek** [comment]
Great, thank you, I'm closing this one.
